/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'mark' at '4/21/16 11:58 AM' with Gradle 2.12
 *
 * @author mark, @date 4/21/16 11:58 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
