/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'mark' at '4/21/16 11:58 AM' with Gradle 2.12
 *
 * @author mark, @date 4/21/16 11:58 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
